### PR TITLE
Adding support for multiple channels and perchannel githooks

### PR DESCRIPTION
**Pull request by ragingpastry**
I just came across this today and made some changes of my own to suit the needs of my organization. Hopefully this helps others.

### CODE REVIEW

**Comment by ragingpastry** [comment]
I'm not sure I understand what you mean with #1. Copying the mattermost_webook_url would result in gitlab firing off its webhook to the wrong place would it not?

**Comment by chengweiv5** [comment]
@ragingpastry just like #4

**Comment by ragingpastry** [comment]
Excellent. Apparently I didn't have my coffee after first reading your comments. I went ahead and modified my fork last week (and it looks like we basically made the same changes except for the variable renaming).

**Comment by chengweiv5** [comment]
@ragingpastry the fact is I'm not good at English, so you didn't understand me at first. :-)

**Comment by jar3b** [comment]
Hello! One question: why do you want to be able to change the hook url for each project instead of specifying only a particular channel?
Base logic (first case):
1. We have a running integration worker (web-server on specific port).
2. For each gitlab project, you pass your mattermost hook url as a webhook parameter (for doing this you need to create a separate mattermost hook for each channel, right?)
My opinion (second case):
1. The same way, we have one running worker.
2. But! Instead, you can create one hook in mattermost and simply specify only the channel name for a particular gitlab project.

So, if you want to specify different hook url, you can create 2 and more outgoing hooks in gitlab project (and must start 2 integration worker processes). But why if select specified channel is our target. I think in mattermost: 1 hook - 1 external app, or it's wrong? 

In this PR hid a good idea, but a usage (IMO) may be little bit different: not for specifying a channel, but for ability to install one integration worker per one gitlab machine that can send data to different Mattermost instances.

**Pull request closed without merging**
