### PR TITLE
Push event add commits link

### PR DESCRIPTION
**Pull request by Aschen**
Hi,

I have added a link to the last pushed commits in Push Event.

capture_mattermost_python-convertimage

### CODE REVIEW

**Comment by Aschen** [comment]
Sorry for the multiples commit, I think it would work even if I don't install pip and coveralls on my computer but I was wrong.. ^^'

**Comment by NotSqrt** [comment]
Thanks!

I'm about to be on holidays, so I won't merge this immediately..

**Comment by Aschen** [comment]
Ok there is no hurry, I use my own version meanwhile.

Happy holidays :)

**Comment by NotSqrt** [comment]
Superseded by #24

**Pull request closed without merging**
